import type { SupabaseClient } from "@supabase/supabase-js";
import type {
  Invitation,
  InvitationStatus,
  MemberRole,
  Result,
} from "@/lib/domain/types";

/**
 * Invitation service — owns invitation data access: creating, listing,
 * revoking, and redeeming invites. Single responsibility: invitations.
 */
export class InvitationService {
  constructor(private readonly supabase: SupabaseClient) {}

  /** Pending/recent invitations for an org, newest first. */
  async listInvitations(orgId: string): Promise<Result<Invitation[]>> {
    const { data, error } = await this.supabase
      .from("invitations")
      .select("id, token, role, status, created_at")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });

    if (error) return { ok: false, error: error.message };

    const invites: Invitation[] = (data ?? []).map((row) => ({
      id: row.id as string,
      token: row.token as string,
      role: row.role as MemberRole,
      status: row.status as InvitationStatus,
      createdAt: row.created_at as string,
    }));

    return { ok: true, data: invites };
  }

  /** Create an invitation with a role; token is generated by the DB. */
  async createInvitation(
    orgId: string,
    role: MemberRole,
    createdBy: string
  ): Promise<Result<Invitation>> {
    const { data, error } = await this.supabase
      .from("invitations")
      .insert({ org_id: orgId, role, created_by: createdBy })
      .select("id, token, role, status, created_at")
      .single();

    if (error) return { ok: false, error: error.message };

    return {
      ok: true,
      data: {
        id: data.id as string,
        token: data.token as string,
        role: data.role as MemberRole,
        status: data.status as InvitationStatus,
        createdAt: data.created_at as string,
      },
    };
  }

  /** Revoke a pending invitation. */
  async revokeInvitation(invitationId: string): Promise<Result<null>> {
    const { error } = await this.supabase
      .from("invitations")
      .update({ status: "revoked" })
      .eq("id", invitationId);

    if (error) return { ok: false, error: error.message };
    return { ok: true, data: null };
  }

  /** Redeem an invite token for the current user via the DB function. */
  async redeemInvitation(token: string): Promise<Result<string>> {
    const { data, error } = await this.supabase.rpc("redeem_invitation", {
      invite_token: token,
    });

    if (error) return { ok: false, error: error.message };
    return { ok: true, data: data as string };
  }
}
